# Generated by Django 6.0.7 on 2026-10-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processstep',
            name='step_type',
            field=models.CharField(choices=[('Trigger', 'Gatilho'), ('Condition', 'Regra Condicional'), ('Human_task', 'Aprovação Manual'), ('Automated', 'Ação Automática')], max_length=20),
        ),
    ]
